version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
  migrate:
    build:
      context: ./migrate
      dockerfile: Dockerfile
    restart: unless-stopped
    command: [ "tail", "-F", "anything" ]
    depends_on:
      - postgres
    volumes:
      - ./migrate/migrations:/usr/src/app/migrations
    env_file:
      - ./.env
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "db"
      POSTGRES_PASSWORD: "db"
    volumes:
      - ./data/pg/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 60s
      retries: 4
    ports:
      - "5432:5432"